version: 2
updates:
  # Elixir dependencies
  - package-ecosystem: "mix" 
    directory: "/" 
    schedule:
      interval: "weekly" 
    open-pull-requests-limit: 10 

   # GitHub Actions
  - package-ecosystem: "github-actions" 
    directory: "./.github" 
    schedule:
      interval: "weekly" 
    open-pull-requests-limit: 10 
   
   # testing
  - package-ecosystem: "npm" 
    directory: "../testing" 
    schedule:
      interval: "weekly" 
    open-pull-requests-limit: 10 
