name: Deploy main branch to dev environment on Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: projectstake/workflows/.github/workflows/deploy.yml@main
    with:
      app: chainstaker-dev
      host: chainstaker.dev
    secrets:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
